Fix flake and pylint warnings.
lint run-test: commands[1] | flake8 /home/pc3/repo/fiuba/introDistribuidos/TP1IntroDistribuidos
./salida.py:3:1: E302 expected 2 blank lines, found 1
./salida.py:13:24: E221 multiple spaces before operator
./salida.py:22:1: W391 blank line at end of file
./cliente.py:1:1: F403 'from socket import *' used; unable to detect undefined names
./cliente.py:4:16: F405 'socket' may be undefined, or defined from star imports: socket
./cliente.py:4:23: F405 'AF_INET' may be undefined, or defined from star imports: socket
./cliente.py:4:32: F405 'SOCK_DGRAM' may be undefined, or defined from star imports: socket
./cliente.py:5:10: E225 missing whitespace around operator
./cliente.py:6:37: E231 missing whitespace after ','
./cliente.py:9:21: W292 no newline at end of file
./parametros.py:2:1: F403 'from salida import *' used; unable to detect undefined names
./parametros.py:3:1: E302 expected 2 blank lines, found 0
./parametros.py:5:18: F405 'EnumSalida' may be undefined, or defined from star imports: salida
./parametros.py:12:5: E303 too many blank lines (2)
./parametros.py:20:35: F405 'EnumSalida' may be undefined, or defined from star imports: salida
./parametros.py:23:35: F405 'EnumSalida' may be undefined, or defined from star imports: salida
./pruebasalida.py:1:1: F403 'from salida import *' used; unable to detect undefined names
./pruebasalida.py:3:10: F405 'Salida' may be undefined, or defined from star imports: salida
./pruebasalida.py:3:17: F405 'EnumSalida' may be undefined, or defined from star imports: salida
./pruebasalida.py:8:10: F405 'Salida' may be undefined, or defined from star imports: salida
./pruebasalida.py:8:17: F405 'EnumSalida' may be undefined, or defined from star imports: salida
./pruebasalida.py:13:10: F405 'Salida' may be undefined, or defined from star imports: salida
./pruebasalida.py:13:17: F405 'EnumSalida' may be undefined, or defined from star imports: salida
./pri.py:1:9: W292 no newline at end of file
./upload.py:2:1: F403 'from salida import *' used; unable to detect undefined names
./upload.py:3:1: F403 'from parametros import *' used; unable to detect undefined names
./upload.py:6:9: F405 'Parametros' may be undefined, or defined from star imports: parametros, salida
./upload.py:21:10: F405 'Salida' may be undefined, or defined from star imports: parametros, salida
./upload.py:30:1: W391 blank line at end of file
./main.py:4:80: E501 line too long (98 > 79 characters)
./servidor.py:1:1: F403 'from socket import *' used; unable to detect undefined names
./servidor.py:3:16: F405 'socket' may be undefined, or defined from star imports: socket
./servidor.py:3:23: F405 'AF_INET' may be undefined, or defined from star imports: socket
./servidor.py:3:32: F405 'SOCK_DGRAM' may be undefined, or defined from star imports: socket

__init__.py:1:0: F0010: error while code parsing: Unable to load file __init__.py:
[Errno 2] No such file or directory: '__init__.py' (parse-error)
ERROR: InvocationError for command /home/pc3/repo/fiuba/introDistribuidos/TP1IntroDistribuidos/.tox/lint/bin/pylint . --output-format=colorized (exited with code 1)

__init__.py:1:0: C0103: Module name TP1IntroDistribuidos doesn't conform to snake_case naming style (invalid-name)
ERROR: InvocationError for command /home/pc3/repo/fiuba/introDistribuidos/TP1IntroDistribuidos/.tox/lint/bin/pylint . --output-format=colorized (exited with code 16)